steps:
  - id: build-api
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Containerfile.api
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/api:${BUILD_ID}
      - .

  - id: build-frontend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - frontend/Containerfile
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/frontend:${BUILD_ID}
      - frontend

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/api:${BUILD_ID}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/frontend:${BUILD_ID}

substitutions:
  _REGION: asia-northeast1
  _REPOSITORY: onagawa-source-chat

options:
  logging: CLOUD_LOGGING_ONLY
