"""Export the API-owned scope schema and TypeScript types; --check for CI."""
from pathlib import Path
import argparse
import json
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from retrieval.source_scope import EvidenceScope  # noqa: E402


def export():
    schema = EvidenceScope.model_json_schema()

    def ts(node):
        if '$ref' in node:
            return node['$ref'].split('/')[-1]
        if 'anyOf' in node:
            return ' | '.join(ts(value) for value in node['anyOf'])
        if 'const' in node:
            return json.dumps(node['const'])
        if 'enum' in node:
            return ' | '.join(json.dumps(value) for value in node['enum'])
        kind = node.get('type')
        if kind == 'object':
            required = node.get('required', [])
            return '{\n' + '\n'.join('  '+key+('' if key in required else '?')+': '+ts(value)+';'
                                    for key, value in node.get('properties', {}).items()) + '\n}'
        return {'string': 'string', 'integer': 'number', 'number': 'number', 'boolean': 'boolean', 'null': 'null'}[kind]

    output = '// Generated by scripts/export_chat_scope.py. Do not edit by hand.\n'
    for name, definition in schema['$defs'].items():
        output += f'export type {name} = {ts(definition)};\n\n'
    output += f'export type EvidenceScope = {ts(schema)};\n\n'
    output += 'export const evidenceScopeSchema = '+json.dumps(schema, sort_keys=True, indent=2)+' as const;\n'
    return output


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = Path(__file__).resolve().parents[1] / 'frontend/lib/generated/chat-scope.ts'
    expected = export()
    if args.check:
        if not target.exists() or target.read_text() != expected:
            raise SystemExit('Chat scope contract is stale. Run scripts/export_chat_scope.py.')
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(expected)
