"use client";

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Locale = "en" | "ja";
export type ThemeMode = "light" | "dark" | "system";
export type Density = "comfortable" | "compact";
export type SidebarMode = "expanded" | "compact";
export type Accent = "ocean" | "violet" | "amber";

export type AppPreferences = {
  locale: Locale;
  theme: ThemeMode;
  density: Density;
  sidebar: SidebarMode;
  accent: Accent;
  reducedMotion: boolean;
};

const STORAGE_KEY = "onagawa-app-preferences";

export const defaultPreferences: AppPreferences = {
  locale: "en",
  theme: "light",
  density: "comfortable",
  sidebar: "expanded",
  accent: "ocean",
  reducedMotion: false,
};

const messages = {
  en: {
    nav: {
      overview: "Overview",
      explore: "Explore",
      data: "Data",
      database: "Database",
      pipeline: "Pipeline",
      provenance: "Provenance",
      evaluation: "Evaluation",
      chat: "Chat",
      admin: "Admin",
      system: "System",
      debug: "Debug",
      feedback: "Feedback",
      users: "Users",
      settings: "Settings",
    },
    settings: {
      title: "Settings",
      intro: "Personalize the research workspace. Preferences are saved in this browser and apply across the app.",
      appearance: "Appearance",
      appearanceHint: "Choose how the interface looks and feels.",
      theme: "Theme",
      themeHint: "Light, dark, or follow your operating system.",
      light: "Light",
      dark: "Dark",
      system: "System",
      language: "Language",
      languageHint: "Choose the language for the app shell and settings.",
      english: "English",
      japanese: "日本語",
      interface: "Interface",
      interfaceHint: "Tune density, navigation, color, and motion.",
      density: "Density",
      comfortable: "Comfortable",
      compact: "Compact",
      sidebar: "Sidebar",
      expanded: "Expanded",
      narrow: "Narrow",
      accent: "Accent color",
      ocean: "Ocean",
      violet: "Violet",
      amber: "Amber",
      reducedMotion: "Reduce interface motion",
      reducedMotionHint: "Minimize transitions and animated effects.",
      preview: "Preview",
      previewHint: "A small preview of your current visual preferences.",
      previewTitle: "Research workspace",
      previewText: "Evidence, provenance, and analysis in one place.",
      active: "Active",
      reset: "Reset preferences",
      saved: "Saved automatically",
      resetConfirm: "Preferences reset to the default light theme.",
    },
  },
  ja: {
    nav: {
      overview: "概要",
      explore: "探索",
      data: "データ",
      database: "データベース",
      pipeline: "パイプライン",
      provenance: "プロヴナンス",
      evaluation: "評価",
      chat: "チャット",
      admin: "管理",
      system: "システム",
      debug: "デバッグ",
      feedback: "フィードバック",
      users: "ユーザー",
      settings: "設定",
    },
    settings: {
      title: "設定",
      intro: "研究ワークスペースをカスタマイズします。設定はこのブラウザに保存され、アプリ全体に反映されます。",
      appearance: "外観",
      appearanceHint: "インターフェースの見た目と操作感を選択します。",
      theme: "テーマ",
      themeHint: "ライト、ダーク、またはOSの設定に合わせます。",
      light: "ライト",
      dark: "ダーク",
      system: "システム",
      language: "言語",
      languageHint: "アプリのシェルと設定画面の言語を選択します。",
      english: "English",
      japanese: "日本語",
      interface: "インターフェース",
      interfaceHint: "密度、ナビゲーション、色、動きを調整します。",
      density: "表示密度",
      comfortable: "標準",
      compact: "コンパクト",
      sidebar: "サイドバー",
      expanded: "展開",
      narrow: "コンパクト",
      accent: "アクセントカラー",
      ocean: "オーシャン",
      violet: "バイオレット",
      amber: "アンバー",
      reducedMotion: "動きを減らす",
      reducedMotionHint: "画面遷移やアニメーションを最小限にします。",
      preview: "プレビュー",
      previewHint: "現在の外観設定のプレビューです。",
      previewTitle: "研究ワークスペース",
      previewText: "エビデンス、プロヴナンス、分析をひとつの場所に。",
      active: "選択中",
      reset: "設定をリセット",
      saved: "自動保存",
      resetConfirm: "設定をライトテーマの初期値に戻しました。",
    },
  },
} as const;

const japaneseInterface: Record<string, string> = {
  "Primary navigation": "メインナビゲーション",
  "Account access unavailable": "アカウントにアクセスできません",
  "Your invitation may have expired, or this account may be suspended.": "招待の有効期限が切れているか、このアカウントが停止されている可能性があります。",
  "Sign out": "サインアウト",
  "Overview": "概要",
  "Administration": "管理",
  "Administration sections": "管理セクション",
  "Manage access, feedback, operations, and platform diagnostics from one workspace.": "アクセス、フィードバック、運用、プラットフォーム診断を一つのワークスペースで管理します。",
  "Admin overview": "管理概要",
  "Choose a section to manage the application without leaving the administration workspace.": "管理ワークスペース内で操作するセクションを選択してください。",
  "Explore": "探索",
  "Data": "データ",
  "Database": "データベース",
  "Pipeline": "パイプライン",
  "Provenance": "プロヴナンス",
  "Evaluation": "評価",
  "Chat": "チャット",
  "Query": "クエリ",
  "System": "システム",
  "Debug": "デバッグ",
  "Feedback": "フィードバック",
  "Users": "ユーザー",
  "Invite users and manage account roles, types, and status.": "ユーザーを招待し、ロール、種別、状態を管理します。",
  "Review answer ratings, comments, evidence, and trust reports.": "回答評価、コメント、エビデンス、信頼レポートを確認します。",
  "Run and monitor ingestion, analysis, database, and embedding jobs.": "取り込み、分析、データベース、埋め込みジョブを実行・監視します。",
  "Inspect PostgreSQL schema, table contents, and read-only queries.": "PostgreSQLスキーマ、テーブル内容、読み取り専用クエリを確認します。",
  "Monitor service health, artifacts, models, and corpus coverage.": "サービス状態、成果物、モデル、コーパス範囲を監視します。",
  "Inspect raw application, environment, route, cache, and client state.": "アプリ、環境、ルート、キャッシュ、クライアントの生データを確認します。",
  "Settings": "設定",
  "Refresh": "更新",
  "Reset": "リセット",
  "Clear": "クリア",
  "Cancel": "キャンセル",
  "Close": "閉じる",
  "Back": "戻る",
  "Next": "次へ",
  "Previous": "前へ",
  "Search": "検索",
  "Submit": "送信",
  "Loading...": "読み込み中…",
  "Loading": "読み込み中",
  "Loading data.": "データを読み込んでいます。",
  "No data available.": "利用可能なデータがありません。",
  "No results.": "結果がありません。",
  "Request failed": "リクエストに失敗しました",
  "Summary": "概要",
  "Details": "詳細",
  "Status": "ステータス",
  "Results": "結果",
  "Source": "ソース",
  "Sources": "ソース",
  "All": "すべて",
  "All source types": "すべてのソースタイプ",
  "All bays": "すべての湾",
  "All roles": "すべてのロール",
  "Primary": "主要",
  "Linked": "関連",
  "From": "開始",
  "To": "終了",
  "Limit": "上限",
  "Min score": "最小スコア",
  "Role": "ロール",
  "Expansion": "展開",
  "Max linked": "関連上限",
  "Enabled": "有効",
  "Disabled": "無効",
  "Yes": "はい",
  "No": "いいえ",
  "Observations": "観測",
  "CTD": "CTD",
  "Taxa": "分類群",
  "SST": "SST",
  "Derived Analysis": "派生分析",
  "Reliability": "信頼性",
  "Data views": "データ表示",
  "Observation Classes": "観測クラス",
  "Catalog": "カタログ",
  "CTD samples": "CTDサンプル",
  "Taxa samples": "分類群サンプル",
  "SST observations": "SST観測",
  "SST days": "SST日数",
  "CTD variables": "CTD変数",
  "Context rows": "コンテキスト行",
  "Default CTD sample": "既定のCTDサンプル",
  "Default taxa sample": "既定の分類群サンプル",
  "Sample": "サンプル",
  "Depth Profiles": "深度プロファイル",
  "Profile Table": "プロファイルテーブル",
  "Point SST": "地点SST",
  "Daily Regional Range": "日別地域範囲",
  "Explore views": "探索表示",
  "Tables": "テーブル",
  "Evidence": "エビデンス",
  "Table Browser": "テーブルブラウザー",
  "Rows per page.": "1ページあたりの行数。",
  "Column used to sort the displayed table page.": "表示中のテーブルを並べ替える列。",
  "Direction for table sorting.": "テーブルの並べ替え方向。",
  "Ascending": "昇順",
  "Descending": "降順",
  "Time series": "時系列",
  "Maximum points requested for the chart.": "グラフに表示する最大ポイント数。",
  "Sample detail": "サンプル詳細",
  "Evidence documents": "エビデンス文書",
  "Search evidence": "エビデンスを検索",
  "Result Diagnostics": "結果診断",
  "Search query": "検索クエリ",
  "Question": "質問",
  "Enter question": "質問を入力",
  "Quick questions": "クイック質問",
  "Chat settings": "チャット設定",
  "Retrieval": "検索",
  "Generation": "生成",
  "Advanced": "詳細設定",
  "Model": "モデル",
  "Temperature": "温度",
  "Database schema": "データベーススキーマ",
  "Table": "テーブル",
  "Rows in table": "テーブル内の行",
  "Visible rows": "表示行",
  "Table selector": "テーブル選択",
  "Include heavy columns": "重量列を含める",
  "Similarity Probe": "類似性プローブ",
  "Probe": "プローブ",
  "Stage Flow": "ステージフロー",
  "Artifact Availability": "アーティファクトの可用性",
  "Freshness Classes": "鮮度クラス",
  "Readiness Matrix": "準備状況マトリクス",
  "Readiness": "準備状況",
  "Active Background Jobs": "実行中のバックグラウンドジョブ",
  "Raw Sources": "生ソース",
  "Artifact Freshness": "アーティファクトの鮮度",
  "Derived Artifacts": "派生アーティファクト",
  "Stage Catalog": "ステージカタログ",
  "Manual Batch Controls": "手動バッチ制御",
  "Dry run": "ドライラン",
  "Skip SST": "SSTをスキップ",
  "Reset database": "データベースをリセット",
  "Embed during load": "読み込み時に埋め込み",
  "Notes": "メモ",
  "Preflight": "事前確認",
  "Stages": "ステージ",
  "Full rebuild": "完全再構築",
  "Validate only": "検証のみ",
  "Selected Command Plan": "選択したコマンド計画",
  "Per-Stage Logs": "ステージ別ログ",
  "Full Run Log": "全実行ログ",
  "Run History": "実行履歴",
  "Selected Run": "選択した実行",
  "Artifact Diffs": "アーティファクト差分",
  "Manifest JSON": "マニフェストJSON",
  "Log Tail": "ログ末尾",
  "Background Pipeline Job": "バックグラウンドパイプラインジョブ",
  "System architecture flow": "システムアーキテクチャフロー",
  "Source Balance": "ソース構成",
  "Runtime Signals": "ランタイムシグナル",
  "Operational Surface": "運用インターフェース",
  "Interface Register": "インターフェース一覧",
  "Architecture": "アーキテクチャ",
  "Retrieval documents": "検索文書",
  "Registered samples": "登録サンプル",
  "Analysis docs": "分析文書",
  "Reliability docs": "信頼性文書",
  "Client": "クライアント",
  "App": "アプリ",
  "Config": "設定",
  "Selected Environment": "選択環境",
  "Health": "ヘルス",
  "Stats": "統計",
  "Artifacts": "アーティファクト",
  "Datasets": "データセット",
  "Routes": "ルート",
  "Cache": "キャッシュ",
  "Raw Payload": "生ペイロード",
  "API": "API",
  "Ablation Protocol": "アブレーションプロトコル",
  "Ablation Run Controls": "アブレーション実行制御",
  "Ablation estimate": "アブレーション見積もり",
  "Active jobs": "実行中ジョブ",
  "Aggregate Metrics": "集計指標",
  "Analytics Controls": "分析制御",
  "Applied Settings": "適用済み設定",
  "Apply": "適用",
  "Artifact": "アーティファクト",
  "Artifacts loaded.": "アーティファクトを読み込みました。",
  "Artifacts present": "存在するアーティファクト",
  "Ask": "質問する",
  "Asking": "質問中",
  "Auto-refresh": "自動更新",
  "Background Run": "バックグラウンド実行",
  "Baseline": "ベースライン",
  "Build Manifest": "マニフェストを作成",
  "Category Summary": "カテゴリ概要",
  "Chat models": "チャットモデル",
  "Check": "チェック",
  "Citation patterns": "引用パターン",
  "Columns": "列",
  "Compare": "比較",
  "Comparison Report": "比較レポート",
  "Context Ledger": "コンテキスト台帳",
  "Corpus Statistics": "コーパス統計",
  "Corpus ready": "コーパス準備完了",
  "DB docs": "DB文書",
  "Dataset": "データセット",
  "Days": "日数",
  "Debug payload loaded.": "デバッグペイロードを読み込みました。",
  "Depth points": "深度ポイント",
  "Document Trace Index": "文書トレースインデックス",
  "Documents indexed": "索引済み文書",
  "Documents By Source": "ソース別文書",
  "Document limit": "文書上限",
  "Document Lookup": "文書検索",
  "Dominant Groups": "優勢グループ",
  "Download the currently loaded table rows as CSV.": "現在読み込まれているテーブル行をCSVでダウンロードします。",
  "Embedded": "埋め込み済み",
  "Embedding batch": "埋め込みバッチ",
  "Embedding model": "埋め込みモデル",
  "Evaluation views": "評価表示",
  "Existing artifacts": "既存アーティファクト",
  "Failure Surface": "失敗サーフェス",
  "Fetched": "取得済み",
  "Found": "検出",
  "Friedman Omnibus": "Friedman全体検定",
  "FTS": "FTS",
  "Genera": "属",
  "Heavy columns": "重量列",
  "Include embedding treatment": "埋め込み処理を含める",
  "Interfaces": "インターフェース",
  "Invalid": "無効",
  "Key facts": "主要事実",
  "Kraken Top Genera": "Kraken上位属",
  "LLM judge": "LLM判定",
  "Lineage Flow": "系譜フロー",
  "Link": "リンク",
  "Linked cited": "関連引用",
  "Linked evidence": "関連エビデンス",
  "Loading artifacts.": "アーティファクトを読み込んでいます。",
  "Loading corpus workspace.": "コーパスワークスペースを読み込んでいます。",
  "Loading data workspace.": "データワークスペースを読み込んでいます。",
  "Loading database schema.": "データベーススキーマを読み込んでいます。",
  "Loading debug payload.": "デバッグペイロードを読み込んでいます。",
  "Loading evaluation state.": "評価状態を読み込んでいます。",
  "Loading pipeline state.": "パイプライン状態を読み込んでいます。",
  "Loading provenance state.": "プロヴナンス状態を読み込んでいます。",
  "Loading sample.": "サンプルを読み込んでいます。",
  "Manifest Controls": "マニフェスト制御",
  "Max depth": "最大深度",
  "Max SST": "最大SST",
  "Max score": "最大スコア",
  "Mean SST": "平均SST",
  "Mean salinity": "平均塩分",
  "Mean score": "平均スコア",
  "Metric By Mode": "モード別指標",
  "Metric Contract": "指標仕様",
  "Missing req": "不足要件",
  "Mode Category Matrix": "モード・カテゴリ行列",
  "Model runtime": "モデルランタイム",
  "Modified": "更新日時",
  "No documents match the active score threshold.": "現在のスコアしきい値に一致する文書がありません。",
  "No matching evidence records.": "一致するエビデンス記録がありません。",
  "No per-stage log sections available.": "利用可能なステージ別ログがありません。",
  "No pipeline job selected.": "パイプラインジョブが選択されていません。",
  "No profile variables selected.": "プロファイル変数が選択されていません。",
  "No response.": "応答がありません。",
  "No stage log captured.": "ステージログが記録されていません。",
  "No table loaded.": "テーブルが読み込まれていません。",
  "No taxa values for this sample.": "このサンプルの分類群データがありません。",
  "No time-series view for this dataset.": "このデータセットの時系列表示はありません。",
  "Not loaded.": "未読み込みです。",
  "Normalized Artifacts": "正規化アーティファクト",
  "Numeric": "数値",
  "Off": "オフ",
  "Operations": "運用",
  "Order by": "並べ替え列",
  "Path": "パス",
  "Points": "ポイント数",
  "Primary cited": "主要引用",
  "Prompt chars": "プロンプト文字数",
  "Provenance views": "プロヴナンス表示",
  "Quality metrics": "品質指標",
  "Raw ready": "生データ準備完了",
  "Reads >1kb": "1kb超のリード",
  "Reference answer": "参照回答",
  "Refreshing.": "更新しています。",
  "Registered files": "登録ファイル",
  "Report": "レポート",
  "Req context": "要求コンテキスト",
  "Reset all chat controls to defaults.": "すべてのチャット設定を初期値に戻します。",
  "Response": "応答",
  "Retrieval And Citation": "検索と引用",
  "Retrieval Diagnostics": "検索診断",
  "Retrieved Evidence": "取得エビデンス",
  "Row Inspector": "行インスペクター",
  "Run": "実行",
  "Run Detail": "実行詳細",
  "Run Preflight": "実行前確認",
  "Run Selection": "実行選択",
  "Run Summary": "実行概要",
  "Saved runs": "保存済み実行",
  "Schema": "スキーマ",
  "Searching": "検索中",
  "Select a row with a sample_id.": "sample_idのある行を選択してください。",
  "Select a table.": "テーブルを選択してください。",
  "Significant Pairwise Comparisons": "有意なペア比較",
  "Source type": "ソースタイプ",
  "Sources ok": "ソース正常",
  "Standard Protocol": "標準プロトコル",
  "Standard Run Controls": "標準実行制御",
  "Standard estimate": "標準見積もり",
  "Start Ablation": "アブレーション開始",
  "Start Job": "ジョブ開始",
  "Start Standard": "標準実行開始",
  "State": "状態",
  "Statistical Significance": "統計的有意性",
  "Surface T": "表層温度",
  "Text filter": "テキストフィルター",
  "Time": "時刻",
  "Top K": "Top K",
  "Top pairs": "上位ペア",
  "Total": "合計",
  "Total documents": "文書合計",
  "Trace Path": "トレースパス",
  "Trace Rail": "トレースレール",
  "Trace Summary": "トレース概要",
  "Trust Report": "信頼レポート",
  "Updated": "更新済み",
  "User question sent to retrieval and the selected chat model.": "検索と選択したチャットモデルに送信するユーザー質問。",
  "Valid": "有効",
  "Vector": "ベクトル",
  "Variable": "変数",
  "Your account does not have permission to view this page.": "このページを表示する権限がありません。",
  "benchmark questions.": "ベンチマーク質問。",
  "default": "既定値",
  "documents": "文書",
  "fused results for": "融合結果（対象：",
  "linked": "関連",
  "manifest documents.": "マニフェスト文書。",
  "none": "なし",
  "of": "/",
  "primary": "主要",
  "query, inspect, evaluate": "検索・確認・評価",
  "recorded manual runs.": "件の手動実行を記録。",
  "saved runs.": "件の保存済み実行。",
  "stages.": "ステージ。",
  "tables": "テーブル",
  "tracked artifacts.": "件の追跡アーティファクト。",
  "value": "値",
  "Access denied": "アクセス拒否",
  "Analysis": "分析",
  "Analysis views": "分析表示",
  "Artifact Classes": "アーティファクトクラス",
  "Artifact Versions": "アーティファクトバージョン",
  "Audit Warnings": "監査警告",
  "Bay": "湾",
  "CTD casts": "CTDキャスト",
  "CTD docs": "CTD文書",
  "Category": "カテゴリ",
  "Citation Requirements": "引用要件",
  "Citation Resolution": "引用解決",
  "Citations": "引用数",
  "Context cited": "引用済みコンテキスト",
  "Context window": "コンテキストウィンドウ",
  "Coverage": "カバレッジ",
  "Direction": "方向",
  "Displayed": "表示数",
  "Distribution": "分布",
  "Diversity": "多様性",
  "Document": "文書",
  "Dry-Run Controls": "ドライラン制御",
  "Embedded in view": "表示中の埋め込み",
  "Embedding": "埋め込み",
  "Embedding Status": "埋め込み状態",
  "Embedding Treatment": "埋め込み処理",
  "Injected Context": "注入コンテキスト",
  "Judge model": "判定モデル",
  "Kraken genera": "Kraken属数",
  "Limitations": "制限事項",
  "MetaEuk Top Genera": "MetaEuk上位属",
  "MetaEuk genera": "MetaEuk属数",
  "Metagenome docs": "メタゲノム文書",
  "Metric": "指標",
  "Missing": "不足",
  "Mode": "モード",
  "Mode Comparison": "モード比較",
  "Models": "モデル",
  "Modes": "モード数",
  "No record.": "レコードがありません。",
  "No rows.": "行がありません。",
  "None": "なし",
  "Num ctx": "コンテキスト数",
  "Pairs": "ペア数",
  "Pipeline views": "パイプライン表示",
  "Probing": "プローブ中",
  "Prompt Context": "プロンプトコンテキスト",
  "Prompt Diagnostics": "プロンプト診断",
  "Quality Metrics": "品質指標",
  "Question IDs": "質問ID",
  "Questions": "質問数",
  "Quick subset": "クイックサブセット",
  "RAG": "RAG",
  "Raw Trace Payload": "生トレースペイロード",
  "Registry": "レジストリ",
  "Registry records": "レジストリレコード",
  "Repeats": "繰り返し回数",
  "Reset evidence controls.": "エビデンス設定をリセットします。",
  "Retrieval Store": "検索ストア",
  "Rows": "行数",
  "Run Dry-Run": "ドライラン実行",
  "Runs": "実行数",
  "SST docs": "SST文書",
  "Sample Coverage": "サンプルカバレッジ",
  "Samples": "サンプル数",
  "Samples By Bay": "湾別サンプル",
  "Satellite SST": "衛星SST",
  "Score": "スコア",
  "Select all": "すべて選択",
  "Significant": "有意",
  "Significant only": "有意なもののみ",
  "Size": "サイズ",
  "Sort by": "並べ替え",
  "Source Files": "ソースファイル",
  "Source Registration": "ソース登録",
  "Source files": "ソースファイル",
  "Station": "観測点",
  "Tag": "タグ",
  "Text": "テキスト",
  "Trace": "トレース",
  "Trust": "信頼度",
  "Variables": "変数",
  "Variants": "バリアント数",
  "Account type": "アカウント種別",
  "Actions": "操作",
  "Active": "有効",
  "Active accounts": "有効なアカウント",
  "Admin": "管理者",
  "All account types": "すべてのアカウント種別",
  "All ratings": "すべての評価",
  "All reasons": "すべての理由",
  "Answer": "回答",
  "Apply filters": "フィルターを適用",
  "Commercial": "商用",
  "Common reasons": "主な理由",
  "Email": "メールアドレス",
  "Evidence snapshot": "エビデンススナップショット",
  "Expires": "有効期限",
  "Export CSV": "CSVを書き出す",
  "Exporting": "書き出し中",
  "Feedback review": "フィードバック確認",
  "Internal": "内部",
  "Invitations": "招待",
  "Invite": "招待する",
  "Invite account": "アカウントを招待",
  "Last login": "最終ログイン",
  "Loading detail…": "詳細を読み込んでいます…",
  "Negative": "否定的",
  "No accounts.": "アカウントがありません。",
  "No additional comment.": "追加コメントはありません。",
  "No invitations.": "招待がありません。",
  "No reason supplied.": "理由は入力されていません。",
  "No trust report was recorded.": "信頼レポートは記録されていません。",
  "Positive": "肯定的",
  "Question, answer, comment, or user": "質問、回答、コメント、またはユーザー",
  "Rating": "評価",
  "Reason": "理由",
  "Request and prompt metadata": "リクエストとプロンプトのメタデータ",
  "Research": "研究",
  "Researcher": "研究者",
  "Responses": "回答一覧",
  "Review detail": "確認詳細",
  "Select a response to review it.": "確認する回答を選択してください。",
  "Submitted": "送信日時",
  "Suspended": "停止中",
  "Trust report": "信頼レポート",
  "User": "ユーザー",
  "Users and invitations": "ユーザーと招待",
  "Viewer": "閲覧者",
};

type MessageKey = keyof typeof messages.en.settings;

type PreferencesContextValue = {
  preferences: AppPreferences;
  setPreference: <K extends keyof AppPreferences>(key: K, value: AppPreferences[K]) => void;
  resetPreferences: () => void;
  t: (section: "nav" | "settings", key: string) => string;
  ui: (text: string) => string;
};

const PreferencesContext = createContext<PreferencesContextValue | null>(null);

function isPreferences(value: unknown): value is Partial<AppPreferences> {
  return Boolean(value && typeof value === "object");
}

export function AppPreferencesProvider({ children }: { children: ReactNode }) {
  const [preferences, setPreferences] = useState<AppPreferences>(defaultPreferences);
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    try {
      const stored = window.localStorage.getItem(STORAGE_KEY);
      if (stored) {
        const parsed: unknown = JSON.parse(stored);
        if (isPreferences(parsed)) {
          setPreferences({ ...defaultPreferences, ...parsed });
        }
      }
    } catch {
      // A malformed preference should never prevent the app from loading.
    } finally {
      setHydrated(true);
    }
  }, []);

  useEffect(() => {
    if (hydrated) window.localStorage.setItem(STORAGE_KEY, JSON.stringify(preferences));
  }, [hydrated, preferences]);

  useEffect(() => {
    const root = document.documentElement;
    const applyTheme = () => {
      const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
      const resolvedTheme = preferences.theme === "system"
        ? (prefersDark ? "dark" : "light")
        : preferences.theme;
      root.dataset.theme = resolvedTheme;
    };
    root.dataset.density = preferences.density;
    root.dataset.sidebar = preferences.sidebar;
    root.dataset.accent = preferences.accent;
    root.dataset.motion = preferences.reducedMotion ? "reduced" : "full";
    root.lang = preferences.locale;
    applyTheme();
    const media = window.matchMedia("(prefers-color-scheme: dark)");
    media.addEventListener("change", applyTheme);
    return () => media.removeEventListener("change", applyTheme);
  }, [preferences]);

  const value = useMemo<PreferencesContextValue>(() => ({
    preferences,
    setPreference: (key, value) => setPreferences((current) => ({ ...current, [key]: value })),
    resetPreferences: () => setPreferences(defaultPreferences),
    t: (section, key) => {
      const sectionMessages = messages[preferences.locale][section] as Record<string, string>;
      return sectionMessages[key] || key;
    },
    ui: (text) => preferences.locale === "ja" ? japaneseInterface[text] || text : text,
  }), [preferences]);

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}

export function useAppPreferences() {
  const context = useContext(PreferencesContext);
  if (!context) throw new Error("useAppPreferences must be used inside AppPreferencesProvider");
  return context;
}

export type SettingsMessageKey = MessageKey;
